### ISSUE TITLE
DS Gadget not attaching to running game

### ISSUE THREAD

**Issue by Sylk** [JKAnderson/DS-Gadget#10]
I'm running Dark souls remastered and am trying to get this to attach after launching the .exe. However it just sits in a state like this:
![image](https://user-images.githubusercontent.com/11181348/103462947-11d08780-4ce6-11eb-9954-583a957785b1.png)

**Comment by JKAnderson** [comment]
You're looking for this
https://github.com/JKAnderson/DSR-Gadget
