### ISSUE TITLE
dsgadget.exe problem

### ISSUE THREAD

**Issue by fillofillofillo** [JKAnderson/DS-Gadget#11]
i feel kinda dumb asking for this but i can't find a way to run the program, since i can't find the DSgadget.exe file in the extracted folder

**Comment by Rascalnicough** [comment]
> i feel kinda dumb asking for this but i can't find a way to run the program, since i can't find the DSgadget.exe file in the extracted folder

Don't feel dumb. Check out the assembled project here: https://github.com/JKAnderson/DS-Gadget/releases/tag/3.0
