### ISSUE TITLE
Unofficial versions of the game aren't supported

### ISSUE THREAD

**Issue by DumbJoe** [JKAnderson/DS-Gadget#6]
How to fix?

**Comment by JKAnderson** [comment]
Are you using a version of the game other than the latest Steam release?

**Comment by DumbJoe** [comment]
...maybe...

**Comment by JKAnderson** [comment]
Yeah, at the moment only the latest Steam version and the debug exe are supported. May change in the future seeing as you're not even allowed to buy it any more.

**Comment by DumbJoe** [comment]
oh, I was using it on my old disc copy I bought a few years back....so can you make it happen for this version too please? Thanks!

**Comment by r3sus** [comment]
It works already. Could be closed, please. @DumbJoe

**Comment by DumbJoe** [comment]
Are you sure r3sus?

**Comment by r3sus** [comment]
Yes, see the Readme
> Changelog
3.0
AOB scanning instead of hardcoded offsets, aka support for unofficial versions
